# Dockerfile.build
FROM --platform=$TARGETPLATFORM ubuntu:latest

# Install build dependencies
RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    libncurses5-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy source files
WORKDIR /build
COPY . .

# Build
RUN cmake -DCMAKE_BUILD_TYPE=Release . && \
    make && \
    strip multiproc

# Copy to output
CMD cp multiproc /output/
