name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.release.outputs.new_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install semantic-release and plugins
        run: npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/github @semantic-release/git @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Run semantic-release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eo pipefail

          npx semantic-release > semantic-output.log

          echo "Semantic Release output:"
          cat semantic-output.log

          # Extract created tag from output
          version=$(grep -oE 'Created tag v[0-9]+\.[0-9]+\.[0-9]+' semantic-output.log | head -n1 | awk '{print $3}')
          echo "Parsed release version: $version"

          echo "new_tag=$version" >> $GITHUB_OUTPUT

  build:
    name: Build and Upload Binaries
    needs: release
    if: needs.release.outputs.new_tag != ''
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64/v8

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build binary
        run: |
          mkdir -p dist
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --build-arg TARGETARCH=${{ matrix.arch }} \
            --output type=local,dest=./dist \
            -f Dockerfile.build .

      - name: Rename binary
        run: mv dist/multiproc dist/multiproc-${{ matrix.arch }}

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/multiproc-${{ matrix.arch }}
          tag_name: ${{ needs.release.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
